name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build and pack
        run: dotnet build -c Release -o ./output
        working-directory: ./MightyLittleGeodesyPackage
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: dll
          path: ./output/*.dll 
      - name: Build
        run: dotnet build
      - name: Test with the dotnet CLI
        run: |
          dotnet build -c Release
          dotnet test -c Release --no-build
